version: 2
jobs:
  build:
    docker:
    - image: 'circleci/openjdk:8-jdk'
    working_directory: ~/repo
    environment:
      JVM_OPTS: '-Xmx3200m'
      TERM: dumb
    steps:
    - checkout
    - run: 'chmod +x gradlew'
    - run: './gradlew clean fatJar dependencyCheckAnalyze'
